# Generated by Django 5.1.6 on 2025-02-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=200)),
                ('Designation', models.CharField(max_length=200)),
                ('Salary', models.FloatField(max_length=200)),
                ('Experience', models.SmallIntegerField(max_length=200)),
            ],
        ),
    ]
