# Generated by Django 5.1.6 on 2025-02-25 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('l_id', models.AutoField(primary_key=True, serialize=False)),
                ('l_name', models.CharField(max_length=200)),
                ('l_city', models.CharField(max_length=200)),
                ('l_state', models.CharField(max_length=200)),
                ('l_country', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.CharField(max_length=200)),
                ('Adress', models.CharField(max_length=200)),
                ('Emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='department_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='employees.department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='l_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.location'),
        ),
    ]
