# Generated by Django 5.1.6 on 2025-02-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_department_location_contact_employee_department_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Experience',
            field=models.SmallIntegerField(),
        ),
    ]
