# Generated by Django 5.1.6 on 2025-02-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_rename_emp_id_contact_emp_rename_l_id_department_l_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
    ]
