# Generated by Django 5.1.6 on 2025-02-25 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='d_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='employee.department'),
            preserve_default=False,
        ),
    ]
