# Generated by Django 5.1.6 on 2025-02-25 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0003_department_rename_first_name_employee_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Employee.department'),
            preserve_default=False,
        ),
    ]
