# Generated by Django 5.1.6 on 2025-02-25 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_location_department_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='location',
        ),
    ]
