# Generated by Django 5.1.6 on 2025-02-25 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0006_remove_department_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Employee.location'),
            preserve_default=False,
        ),
    ]
