# Generated by Django 5.1.6 on 2025-02-25 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('Sem_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('Sem', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Usn', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=200)),
                ('Branch', models.CharField(max_length=100)),
                ('Current_sem', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('Sub_Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Sub_name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marks', models.FloatField(max_length=100)),
                ('Sem_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.semester')),
                ('Student_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
                ('Sub_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.subject')),
            ],
        ),
    ]
