# Generated by Django 5.1.6 on 2025-02-26 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('B_Id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('B_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Catageory',
            fields=[
                ('Cat_Id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('Cat_name', models.CharField(max_length=200)),
                ('Parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.catageory')),
            ],
        ),
    ]
