# Generated by Django 5.1.6 on 2025-02-25 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('b_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('b_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=20)),
                ('pat_id', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('P_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=20)),
                ('b_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.brand')),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
    ]
