# Generated by Django 5.1.6 on 2025-02-26 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_catageory_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('P_Id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('P_name', models.CharField()),
                ('B', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.brand')),
                ('Cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.catageory')),
            ],
        ),
    ]
